In [1]:
import numpy as np

In [3]:
d2array = np.array([[1,3,5],[2,4,6],[6,4,2]])

In [4]:
d2array

array([[1, 3, 5],
       [2, 4, 6],
       [6, 4, 2]])

## insertion
### time complexity O(mn) 

In [5]:
## adding column in the start of array
new2darray = np.insert(d2array,0,[[1,2,3]],axis=1)

In [6]:
new2darray

array([[1, 1, 3, 5],
       [2, 2, 4, 6],
       [3, 6, 4, 2]])

In [7]:
## adding new row
new2darray = np.insert(d2array,0,[[1,2,3]],axis=0)

In [8]:
new2darray

array([[1, 2, 3],
       [1, 3, 5],
       [2, 4, 6],
       [6, 4, 2]])

In [9]:
## adding 2nd row
new2darray = np.insert(d2array,1,[[1,2,3]],axis=0)

In [10]:
new2darray

array([[1, 3, 5],
       [1, 2, 3],
       [2, 4, 6],
       [6, 4, 2]])

In [13]:
# time complexity is O(1)
np.append(d2array,[[1,2,3]],axis=0) ## new row is added is end of the array

array([[1, 3, 5],
       [2, 4, 6],
       [6, 4, 2],
       [1, 2, 3]])

## access two dimention array
### time complexity O(1) & space complexity is O(1)

In [14]:
new2darray

array([[1, 3, 5],
       [1, 2, 3],
       [2, 4, 6],
       [6, 4, 2]])

In [15]:
len(new2darray)

4

In [16]:
len(new2darray[0])

3

In [18]:
def access(array,rowindex,colindex):
    if rowindex >= len(array) and colindex >= len(array[0]):
        print("incorrect index")
    else:
        print(array[rowindex][colindex])

access(new2darray,3,2)

2


## traversing(visiting) 2D array
### time complexity O(mn) or O(n^2) & space complexity is O(1)

In [20]:
def traversing(array):
    for m in range(len(array)):
        for n in range(len(array[0])):
            print(array[m][n])

traversing(new2darray)

1
3
5
1
2
3
2
4
6
6
4
2


## searching an element
### time complexity O(mn) & space complexity is O(1)

In [25]:
def traversing(array,value):
    for m in range(len(array)):
        for n in range(len(array[0])):
            if array[m][n] == value:
                return "index is found "+str(m)+", "+str(n)
    return "value not found"

traversing(new2darray,6)

'index is found 2, 2'

In [24]:
new2darray

array([[1, 3, 5],
       [1, 2, 3],
       [2, 4, 6],
       [6, 4, 2]])

## deleting row or column for 2D array
### time complexity O(mn) 

In [26]:
new2darray

array([[1, 3, 5],
       [1, 2, 3],
       [2, 4, 6],
       [6, 4, 2]])

In [27]:
np.delete(new2darray,0,axis=1)

array([[3, 5],
       [2, 3],
       [4, 6],
       [4, 2]])

In [28]:
np.delete(new2darray,0,axis=0)

array([[1, 2, 3],
       [2, 4, 6],
       [6, 4, 2]])

In [29]:
np.delete(new2darray,1,axis=0)

array([[1, 3, 5],
       [2, 4, 6],
       [6, 4, 2]])